### ISSUE TITLE
Missing Sources

### ISSUE THREAD

**Issue by DavidNgoDev** [LionSec/katoolin#153]
E: Unable to locate package acccheck
E: Unable to locate package http-tunnel
E: Unable to locate package acccheck

**Comment by CryptoCanuck** [comment]
your archive-keyring package is outdated. this should fix it:

sudo su
wget -q -O - https://archive.kali.org/archive-key.asc | apt-key add
apt update

**Comment by DavidNgoDev** [comment]
Thanks, I will try this when I get home.

**Comment by DavidNgoDev** [comment]
Still getting the same error. I've tried removing the packages from the script and still no luck. Also tried it on a fresh install of Ubuntu. Both 16.4 and 18

**Comment by ballo** [comment]
Same error here, using Devuan.
